### ISSUE TITLE
Question:  Support for Unix Domain Socket and example

### ISSUE THREAD

**Issue by rohitjoshi** [tower-rs/tower#126]
Do we have an example of Unix domain socket support?

**Comment by rohitjoshi** [comment]
@callerche  planning to implement Redis protocol interface which internally connects to remove DB.

I did implement using ‘mio’ and wanted to leverage many towers modules like rate limit, reconnect, bufffer etc

**Comment by carllerche** [comment]
I think this might be a good case for tokio-tower (which is in progress). Thoughts @jonhoo

**Comment by jonhoo** [comment]
As long as you have an `AsyncRead` and `AsyncWrite` (which Unix domain sockets are iirc), you should be able to turn that into `Stream` + `Sink` with a `tokio::codec` (or by writing your own if you're so inclined). Once you have that, you can indeed use [`tokio-tower`](https://github.com/tower-rs/tokio-tower-wip) to move from `Stream + Sink` to `Service` :)

@carllerche maybe we should publish `tokio-tower 0.0.1` so that we get docs up on docs.rs?

**Comment by carllerche** [comment]
The short answer is, Tower is decoupled from UDS or TCP.

You would implement `Service` for Redis, which is request / response based. Once you have that, you can take advantage of all the middleware provided here.

The easiest way to do that, as mentioned, would be `tokio-tower`. With `tokio-tower`, you provide a "transport" which is a type that implements `Stream + Sink`.

And the easiest way to get a transport, is to use a codec :)

(we really should have full stack docs for this).

1. Start with UnixStream
2. Implement your codec (`Encoder + Decoder`) for your redis protocol (https://docs.rs/tokio/0.1.13/tokio/codec/index.html).
3. Call `MyCodec.framed(my_stream)` (https://docs.rs/tokio/0.1.13/tokio/codec/trait.Decoder.html#method.framed), you now have a transport.
4. Pass your transport to `tokio-tower` (not released yet, but we will do that asap).

At that point, you have your `Service` handle for the redis protocol. Then, you can use all the middleware.

**Comment by jonhoo** [comment]
:+1: for full stack docs! :D

**Comment by carllerche** [comment]
Tracking documentation with #33.
