### ISSUE TITLE
rfc bikeshed: Name `Layer` / `Middleware` / `WrapService` trait.

### ISSUE THREAD

**Issue by carllerche** [tower-rs/tower#167]
Follow up from #163

We are in agreement that we need a trait to do what the PR proposes, but what to name it? Such is the life of writing software... We also cannot block indefinitely on debating naming, so lets spend a short amount of time continuing the discussion then vote.

I will post a comment per option. Options are listed alphabetically. Discussion can happen below.

## Option zero: Do not introduce a trait.

The `Middleware` trait is very similar to the `Service` trait in that it has a function that takes an argument and returns an argument.

`Middleware` is "just" a service where the request is a service and the response is a service.

#### Pros

- It does not add a new trait.

#### Cons

- It abuses the `Service` trait a bit. `Middleware` does not need `poll_ready` and it does not need to return a future.

**Comment by carllerche** [comment]
## `Middleware`

#### Pros:

- Lots of precedence in other ecosystems.

#### Cons:

- The name is pretty long
- The trait itself isn't actually "middleware". It is more of a "middleware factory". Given a service, it initializes a middleware with that service. That said, you could consider the factory the middleware.

**Comment by carllerche** [comment]
## `WrapService`

Proposed [here](https://github.com/tower-rs/tower/pull/163#issuecomment-466837284). See this comment for a detailed argument.

#### Pros:

- The name most accurately describes what implementations of the trait do.
- Does not introduce a new name in the code base.

#### Cons:

- Documentation will still talk about "middleware" (using either the word "middleware" or layer"), however there will be no type in the code base using that name. Documentation would need to say something like "Middleware [...] implement `WrapService`".

**Comment by jonhoo** [comment]
To bring over one key idea from https://github.com/tower-rs/tower/pull/163#issuecomment-466837284:
If we put `where T: WrapService` in the user-facing API, users might get confused since the docs will be talking about "middleware" or "layer". After all, they've never heard of `WrapService`, nor do I think they _should_. That's an implementation detail that they shouldn't need to be aware of. Instead, I proposed we fix this with a type alias:

```rust
type Middleware = WrapService;
```

This way, we can use `where T: Middleware` in all user-facing method signatures, while still having the trait be named according to what it does. I like this type aliasing because it makes explicit the observation in tower that middleware is really just `Service` wrapping `Service` wrapping `Service`.

**Comment by tobz** [comment]
Vote: `Middleware`.

Reason: While this trait may represents a type which can generating a struct that represents the _actual_ middleware, the trait ultimately represents a piece of middleware... whether a service builder is taking it directly or using it as a factory to generate the real struct.

I think that most people, following along with the reasoning of "lots of precedence", will look at something like `ServiceBuilder` and the `push`/`middleware` methods and it will immediately make sense to them.

**Comment by carllerche** [comment]
Based off if discussion in Gitter, consensus is heading towards **`Layer`** as the winner.

Any objections?
