### ISSUE TITLE
buffer: Provide mechanism to lazily spawn the worker

### ISSUE THREAD

**Issue by LucioFranco** [tower-rs/tower#242]
Since `DefaultExecutor::current` is lazy, it should be possible to delay the spawning of the worker task until the point of the first poll_ready/call.

**Comment by carllerche** [comment]
Additionally, this would transition `Buffer::new` to not require a `Result`, potentially meaning that the pattern for layers is to do setup work lazily. In this case, `Result` could be removed from the `Layer` trait as well.

The downside is `Buffer::poll_ready` would need to make an atomic check each call to see if the worker has been spawned in order to lazily spawn it.

**Comment by seanmonstar** [comment]
It does sound like a nice goal, the extra atomic is unfortunate.

**Comment by carllerche** [comment]
Another downside is that this would impose the executor generic on the `Buffer` type...

**Comment by jonhoo** [comment]
I agree with @seanmonstar here that the extra atomic is pretty sad. I'm also not a huge fan of us doing "work" in `poll_ready`. I'm not sure how important this is though? Is there an easy way for people to work around it manually? Maybe a `new_lazy` constructor would be a way to go?

**Comment by LucioFranco** [comment]
well, I think it may make sense to provide another buffer type such as `BufferLazy` so you can choose your trade offs. The big issue with the current buffer is it requires you to be in a futures context to spawn the worker right away but this isnt always the case for everyone and for people maybe thinking of using a sync version of tower. But I also do not want everyone paying this trade off.

I also do believe the cost should be minor once the worker is already spawned but im not sure.

**Comment by jonhoo** [comment]
This is now possible with `Buffer::pair`.
