### ISSUE TITLE
Question: best practice for timing out poll_ready?

### ISSUE THREAD

**Issue by myagley** [tower-rs/tower#648]
The timeout service allows a request to be timed out. However, it appears that the timeout timer begins only after the inner service is ready, and only applies to the `call`.  (i.e., the timer is setup in the `call` and only affects the returned future.)

Is there a recommended way to timeout starting with the `poll_ready`? An example scenario is a stack using Reconnect, where the endpoint can't be reached/connected. Reconnect will continue to return `poll_ready` `Pending` until connected, and a caller will wait indefinitely for the service to become ready.

Is there support in tower to timeout the `poll_ready`, or should this be handled by the caller? Or am I missing something obvious?

**Comment by olix0r** [comment]
I think this is generally handled by the caller with something like:

```rust
let svc = tokio::time::timeout(timeout, svc.ready()).await?;
```
or
```rust
let rsp = tokio::time::timeout(timeout, svc.oneshot(req)).await?;
```

While it's definitely pretty easy to write a tower middleware that times out when a service that becomes ready, I'm not sure how useful it really is for a readiness timeout to be encoded into the stack -- all it can really do is cause the whole stack to become defunct (by returning an error in poll_ready), so it's generally up to the caller to figure out how long it wants to wait. I could probably be convinced otherwise, though :)

**Comment by myagley** [comment]
Thanks for the response. This makes sense. I figured that timing out the `poll_ready` should leave the service unusable (which is not usually what you want). Thanks for confirming.
