### ISSUE TITLE
Publish release without pin-project (with pin-project-lite)

### ISSUE THREAD

**Issue by peter-kehl** [tower-rs/tower#742]
Version 0.4.13 still depends on `pin-project`. But `master` got rid of it, and uses `pin-project-lite` only - thank you.

Unfortunately, `pin-project` pulls old `syn 1.0.109`. But `axum-core` -> `async-trait` uses `syn 2.0.5`. That means longer build times...

Output of `cargo hackerman explain syn` on https://github.com/peter-kehl/rusti :
![image](https://github.com/tower-rs/tower/assets/4270240/8de353d7-f4c4-4ea3-9c15-50c0b74f45c0)

See also [cargo hackerman](https://github.com/pacak/hackerman/blob/master/README.md).

Please, consider disecting out and having a `pin-project-lite`-only release. Otherwise take this as a big "+1" for #722.

**Comment by pacak** [comment]
> Please, consider disecting out and having a pin-project-lite-only release.

FWIW recently `pin-project` 1.1.1 uses syn 2. All that `tower` needs to do is to update to use a new version.

**Comment by davidpdrsn** [comment]
Tower's master branch has breaking changes. So a new release would mean a new major. So first we have to decide on whether to merge other breaking PRs first. We already have an [issue for that](https://github.com/tower-rs/tower/issues/722).

Regarding pin-project, Tower 0.4.x depends on pin-project as

```
pin-project = { version = "1", optional = true }
```

[here](https://github.com/tower-rs/tower/blob/tower-0.4.13/tower/Cargo.toml#L82). So a `cargo update` in your crate should update to pin-project 1.1.1 since that is compatible with `pin-project = { version = "1" }`

**Comment by peter-kehl** [comment]
Thank you David and Michael.

Would it be worth mentioning the use of `pin-project = { version = "1.1" }`, maybe somewhere at https://docs.rs/tower/latest/tower? If so, I can provide a PR. I understand that it would be temporary (until the next major Tower version), but it could still help.

**Comment by davidpdrsn** [comment]
I don’t think so. Cargo is gonna automatically pick the latest version of pin-project when you depend on tower and otherwise cargo update should do the trick.

I’ll close this for now but feel free to ask if you have more questions.

**Comment by tobz** [comment]
FWIW, this wasn't completed in one big fell swoop -- there's multiple PRs responsible -- but `pin-project` is in fact no longer used / present in `tower`: it's all `pin-project-lite` now.
