### ISSUE TITLE
Would this project play well with Tower?

### ISSUE THREAD

**Issue by mitchtbaum** [tower-rs/tower#88]
[Thruster](https://github.com/trezm/Thruster) looks like a more fleshed out [tokio-minihttp](https://github.com/tokio-rs/tokio-minihttp).

**Comment by olix0r** [comment]
Hi @mitchtbaum! I'm not trying to be obtuse, but: it depends on what you mean by "play well".

Can projects that use thruster also use components that use tower?  Very likely, since they can integrate via the typical tokio/future primitives.

Are deeper integrations possible? I don't know. The devil's in the details.

**Comment by mitchtbaum** [comment]
:+1: 

Thanks @olix0r
